name: Testcafe

on:
  workflow_dispatch:

permissions:
  contents: read # For checkout
  actions: read # For accessing action outputs

jobs:
  testcafe:
    name: Testcafe e2e Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ci

    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      DID_SERVER_URL: ${{ secrets.DID_SERVER_URL }}
      MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
      MAGIC_API_KEY: ${{ secrets.MAGIC_API_KEY }}
      MAILSLURP_INDEX_ID: ${{ secrets.MAILSLURP_INDEX_ID }}
    steps:
      # Important: When using pull_request_target, checkout the PR code safely
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Use GitHub token with limited permissions
          repository: ${{ github.event.pull_request.head.repo.full_name }} # Checkout from the fork
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Packages
        if: ${{ !contains(github.event.pull_request.title, '[skip test]') }}
        run: npm ci
      - name: Build
        if: ${{ !contains(github.event.pull_request.title, '[skip test]') }}
        run: npm run build:test
      - name: Integration - testcafe
        if: ${{ !contains(github.event.pull_request.title, '[skip test]') }}
        id: testcafe
        run: npm run integration:testcafe:ci
      - name: Upload Artifact
        if: ${{ failure() && steps.testcafe.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: testcafe-fail-screenshots
          path: artifacts
          if-no-files-found: ignore
          retention-days: 1
