export const paths: Record<string, string> = {
  verify: "/(|verify)",
  viewer: "/viewer",
  creator: "/creator",
  form: "/creator/form",
  formPreview: "/creator/form-preview",
  publish: "/creator/publish",
  settings: "/settings",
  addressResolver: "/settings/address-resolver",
  addressBook: "/settings/address-book",
  privacyPolicy: "/privacy-policy",
  termsOfUse: "/terms-of-use",
  wallet: "/wallet",
  endorsementChain: "/endorsement-chain",
  notFound: "*",
}; // note that this is being used to generate sitemap
