export const paths: Record<string, string> = {
  home: "/",
  verify: "/verify",
  viewer: "/viewer",
  faq: "/faq",
  generalFaq: "/faq/general-faq",
  productFaq: "/faq/product-faq",
  eta: "/eta",
  settings: "/settings",
  addressResolver: "/settings/address-resolver",
  addressBook: "/settings/address-book",
  news: "/news",
  newsDetail: "/news/:slug",
  learn: "/learn",
  event: "/event",
  eventDetail: "/event/:slug",
  guidelines: "/guidelines",
  privacyPolicy: "/privacy-policy",
  termsOfUse: "/terms-of-use",
  cost: "/cost",
  partners: "/partners",
  notFound: "*",
};
