// Action Creators
import {createAction, createStandardAction} from "typesafe-actions";
import { Certificate, QRCode, Template } from "../types/tradetrust";

// Actions
const CertificateActionTypes = {
  RESET_CERTIFICATE: "RESET_CERTIFICATE",
  UPDATE_CERTIFICATE: "UPDATE_CERTIFICATE",

  LOADING_STORE_SUCCESS: "LOADING_STORE_SUCCESS",
  LOADING_STORE_FAILURE: "LOADING_STORE_FAILURE",

  VERIFYING_CERTIFICATE: "VERIFYING_CERTIFICATE",
  VERIFYING_CERTIFICATE_SUCCESS: "VERIFYING_CERTIFICATE_SUCCESS",
  VERIFYING_CERTIFICATE_FAILURE: "VERIFYING_CERTIFICATE_FAILURE",

  SENDING_CERTIFICATE: "SENDING_CERTIFICATE",
  SENDING_CERTIFICATE_SUCCESS: "SENDING_CERTIFICATE_SUCCESS",
  SENDING_CERTIFICATE_FAILURE: "SENDING_CERTIFICATE_FAILURE",
  SENDING_CERTIFICATE_RESET: "SENDING_CERTIFICATE_RESET",

  CERTIFICATE_OBFUSCATE_UPDATE: "CERTIFICATE_OBFUSCATE_UPDATE",

  CERTIFICATE_TEMPLATE_REGISTER: "CERTIFICATE_TEMPLATE_REGISTER",
  CERTIFICATE_TEMPLATE_SELECT_TAB: "CERTIFICATE_TEMPLATE_SELECT_TAB",

  CERTIFICATE_PROCESS_QR_CODE: "CERTIFICATE_PROCESS_QR_CODE"
};
// export const loadingStoreSuccess = () => action(CertificateActionTypes.LOADING_STORE_SUCCESS);
// export const verifyCertificate = createStandardAction(CertificateActionTypes.VERIFYING_CERTIFICATE)<Certificate>();
// export const verifyingCertificateSuccess = createStandardAction(CertificateActionTypes.VERIFYING_CERTIFICATE_SUCCESS)<
//   number
// >();
// export const verifyingCertificateFailure = createStandardAction(CertificateActionTypes.VERIFYING_CERTIFICATE_FAILURE)<
//   number
// >();
