import React, { FunctionComponent } from "react";
import { getSortedByDateDesc } from "../../utils";
import { NewsTag, NewsSingle } from "./types";
import { NewsContent } from "./NewsContent/NewsContent";

// massage data by adding slug (base on filename generated by netlify cms) + news type
const getNews = (context: __WebpackModuleApi.RequireContext, type: NewsTag) => {
  const news: NewsSingle[] = [];

  context.keys().forEach((filename: string) => {
    const content = context(filename);
    const slug = filename.replace("./", "").replace(".md", "");
    news.push({
      slug,
      type,
      ...content,
    });
  });

  return news;
};

const importedArticles = require.context("./../../../cms/article/", false, /\.md$/);
const importedNewsletters = require.context("./../../../cms/newsletter/", false, /\.md$/);
const importedPartnerNews = require.context("./../../../cms/partner-news/", false, /\.md$/);
const importedPressReleases = require.context("./../../../cms/press-release/", false, /\.md$/);
const importedSpeeches = require.context("./../../../cms/speech/", false, /\.md$/);

const articles = getNews(importedArticles, NewsTag.ARTICLE);
const newsletters = getNews(importedNewsletters, NewsTag.NEWSLETTER);
const partnerNews = getNews(importedPartnerNews, NewsTag.PARTNER_NEWS);
const pressReleases = getNews(importedPressReleases, NewsTag.PRESS_RELEASE);
const speeches = getNews(importedSpeeches, NewsTag.SPEECH);

export const allNews = getSortedByDateDesc([
  ...articles,
  ...newsletters,
  ...partnerNews,
  ...pressReleases,
  ...speeches,
]);

export const News: FunctionComponent = () => {
  return <NewsContent allNews={allNews} />; // require.context affects tests, storybook compilation, so lets keep them separately in a simple component here
};
