name: Synpress

on:
  pull_request_target:

permissions:
  contents: read # For checkout
  actions: read # For accessing action outputs

jobs:
  synpress:
    # https://github.com/drptbl/synpress-setup-example/blob/1d980157ef343de54f786e1115e1da590f1ba1d1/.github/workflows/e2e.yml#L49-L102
    name: Synpress e2e Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment: "ci forked"
    if: |
      (!contains(github.event.pull_request.title, '[skip test]') &&
      github.event.pull_request.head.repo.full_name != github.repository)

    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      DID_SERVER_URL: ${{ secrets.DID_SERVER_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run e2e tests
        run: docker compose up --build --exit-code-from synpress
      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: tests/e2e/videos
      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
